// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq7Jh51I-HF4mRyrDkuAAvnrj3EJ_VH-0',
    appId: '1:308527717094:web:448c1187d5e4b3ad95f927',
    messagingSenderId: '308527717094',
    projectId: 'belwnhs-d-new-project',
    authDomain: 'belwnhs-d-new-project.firebaseapp.com',
    storageBucket: 'belwnhs-d-new-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRsTn8P4ueh_6xkiT2HQmH9SdOiwExc0I',
    appId: '1:308527717094:android:9edaaf6fb8662f1895f927',
    messagingSenderId: '308527717094',
    projectId: 'belwnhs-d-new-project',
    storageBucket: 'belwnhs-d-new-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPc2m3QGKa_VhjCk8yzLfYuGuj8lWbfkA',
    appId: '1:308527717094:ios:5ed741cdabf9d97c95f927',
    messagingSenderId: '308527717094',
    projectId: 'belwnhs-d-new-project',
    storageBucket: 'belwnhs-d-new-project.appspot.com',
    iosClientId: '308527717094-2q16vfaib2nlnlvlj26lcu7q19bspk6a.apps.googleusercontent.com',
    iosBundleId: 'com.dev-belwnhs.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPc2m3QGKa_VhjCk8yzLfYuGuj8lWbfkA',
    appId: '1:308527717094:ios:5ed741cdabf9d97c95f927',
    messagingSenderId: '308527717094',
    projectId: 'belwnhs-d-new-project',
    storageBucket: 'belwnhs-d-new-project.appspot.com',
    iosClientId: '308527717094-2q16vfaib2nlnlvlj26lcu7q19bspk6a.apps.googleusercontent.com',
    iosBundleId: 'com.dev-belwnhs.mynotes',
  );
}
